version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecuador
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - red

  app1:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: ecuador
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - red

  app2:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: ecuador
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - red

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - red

volumes:
  db_data:

networks:
  red:
